### ISSUE TITLE
PDF Injector - Error: "We can't open this file" - More details provided

### ISSUE THREAD

**Issue by edbitao** [tertek/redcap-pdf-injector#12] opened 2021-09-30 23:59 UTC
Error when previewing the newly injected PDF file.
1. Step1: Add/Upload a new "Injection PDF" (works fine)
2. Step2: Define ALL variables, then click Save (works fine)
3. Error: No preview of the injected PDF file - clicking "Preview" comes with an error **"We can't open this file" - something went wrong (Refresh)**
![image](https://user-images.githubusercontent.com/70118598/135546181-d5ca047e-1757-4bc1-97bb-8a58f0abb8d5.png)
![image](https://user-images.githubusercontent.com/70118598/135546120-143126bd-15fd-427e-a6f6-f56a7c593eed.png)

ENVIRONMENTS:
REDCap 11.1.15 · PHP 7.4.20 (Windows OS) · MariaDB 10.3.12

**Comment by tertek** [comment] 2021-10-01 05:58
Can you please also share the Browser with its Version. 
A screenshot of your module settings on project level would be helfpull as well.

**Comment by edbitao** [comment] 2021-10-01 06:42
Thanks for the email reply.  More details below.

Browser versions:

***@***.***

***@***.***


Project Configuration/Settings:

***@***.***

***@***.***

Eduard Bitao | Senior Systems Analyst | Data and Information Systems
Information and System Performance Directorate | Purchasing & System Performance
Department of Health
Level 1, A Block, 189 Royal Street, EAST PERTH WA 6004
T: (08) 637 31802
E: ***@***.******@***.***>
www.health.wa.gov.au<http://www.health.wa.gov.au/>
Delivering a Healthy WA

**Comment by tertek** [comment] 2021-10-01 06:45
Can you please resend the info? It seems not to be readable...

![image](https://user-images.githubusercontent.com/75415872/135577152-2a15aebb-2c6d-4cf6-9977-3e95d40ee08e.png)

**Comment by edbitao** [comment] 2021-10-01 06:47
Thanks for the email reply.  More details below.

Browser versions:

***@***.***

***@***.***


Project Configuration/Settings:

***@***.***

***@***.***


Eduard Bitao | Senior Systems Analyst | Data and Information Systems
Information and System Performance Directorate | Purchasing & System Performance
Department of Health
Level 1, A Block, 189 Royal Street, EAST PERTH WA 6004
T: (08) 637 31802
E: ***@***.******@***.***>
www.health.wa.gov.au<http://www.health.wa.gov.au/>
Delivering a Healthy WA

**Comment by tertek** [comment] 2021-10-01 06:48
It is still not readable. Maybe some problem with the email client?

**Comment by edbitao** [comment] 2021-10-01 06:51
See if you can view as PDF (attached)

Eduard Bitao | Senior Systems Analyst | Data and Information Systems
Information and System Performance Directorate | Purchasing & System Performance
Department of Health
Level 1, A Block, 189 Royal Street, EAST PERTH WA 6004
T: (08) 637 31802
E: ***@***.******@***.***>
www.health.wa.gov.au<http://www.health.wa.gov.au/>
Delivering a Healthy WA

**Comment by tertek** [comment] 2021-10-01 06:55
No. It seems not to work with your email setup. Please Reply through Github directly so that I can resolve the issue.
It seems to be a Browser related PDF issue.

**Comment by edbitao** [comment] 2021-10-01 07:07
Thanks for the email reply.  More details below.

Browser versions:
 
![image](https://user-images.githubusercontent.com/70118598/135579442-4e9bfd0e-78b5-442c-a03c-224dc50fc2a8.png)


Project Configuration/Settings:
![image](https://user-images.githubusercontent.com/70118598/135579499-9b639803-9695-4c95-8157-84748b2f902a.png)

**Comment by tertek** [comment] 2021-10-01 07:16
The PDF Preview uses [pdf.js](https://github.com/mozilla/pdf.js/) which is not compatible with your Browsers. 
Supported Browsers can be checked here:
https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#which-browsers-are-supported

It is highly recommended to upgrade your Chrome Browser.

**Comment by edbitao** [comment] 2021-10-04 01:19
Thanks Tertek.  I've now followed ALL your instructions with regards to the Browser Supported compatibilities, i.e. see below:
1. Installed Firefox v92.0.1 (32-bit) 
2. Upgraded Google Chrome to v65.0.3323.146 (Official Build) (32-bit)
3. Version 89.0.774.45 (Official build) (64-bit)

But still the same issue.  Perhaps worth mentioning that we have our Firewall setting in place for both REDCap server and MariaDB server and also using WEBDav as our Web Services with **SSL in place**.  NOTE: We have another REDCap vanilla  instances (DEV/UAT) which runs on Linux VM (MySQL DB) but without SSL installed and all works perfectly fine (see screenshot below)

With those notes above for our PROD Server (Windows OS on WEBDav, we're wondering what other external settings we may need to "watch out" that the module is "communicating to"?  So that if there's external sites it's communicating to, we can then adjust (allow) our Firewall settings.

DEV/UAT:
![image](https://user-images.githubusercontent.com/70118598/135780567-80db902e-8576-49e3-9630-049ffe2c99e4.png)


Thanks again for your help.
Eduard

**Comment by edbitao** [comment] 2021-10-04 04:53
On our DEV/UAT (with same browser versions on my PC):
![image](https://user-images.githubusercontent.com/70118598/135796129-7837dfc7-9a8f-49ac-91d2-d39d60e979c4.png)
![image](https://user-images.githubusercontent.com/70118598/135796250-7f8e3b0b-a236-4f10-b872-f8c076d89ba3.png)

**Comment by edbitao** [comment] 2021-10-04 23:58
Hi Tertek,

Still not working after addressing browser compatibility issues.  I’ve provided more details in the Github portal.  Wondering if there’s any external communication that we need to be watching or aware of so that we can adjust our Firewall settings, if need be.  Because, even before upgrading our browsers it was and still is working with our DEV/UAT REDCap instance (although running on Linux – vanilla setup – without SSL enabled).  Hence, not sure if it’s due to SSL/TLS being enabled in our PROD instance and with WEBDav as our Web Services with Firewall rules applied.

Thanks again & regards,

Eduard Bitao | Senior Systems Analyst | Data and Information Systems
Information and System Performance Directorate | Purchasing & System Performance
Department of Health
Level 1, A Block, 189 Royal Street, EAST PERTH WA 6004
T: (08) 637 31802
E: ***@***.******@***.***>
www.health.wa.gov.au<http://www.health.wa.gov.au/>
Delivering a Healthy WA

**Comment by tertek** [comment] 2021-10-05 06:24
Hi,
I am not able to help you here, since this seems unrelated to the module (and even the application itself). I suggest your IT has a look into this.
Thanks

**Comment by edbitao** [comment] 2021-10-05 06:30
Thanks... will delve and investigate further from our end.

**Comment by tertek** [comment] 2021-11-04 14:48
Hi there,
I am sorry to hear that you are experiencing an issue with PDF Injector. 

`Files::getEdocName()` is a method of the REDCap class `Files`. When you upload a file it will be saved in the edoc path referenced by an document id. I cannot follow why this should "never be accessible".

Can you please open up a new Issue describing your exact problem (if error messages please add screenshots), environment (Client: OS, Browser version, Server: OS, Versions), and also pasting a copy of the Javascript Debug output . You can enable Debugging in Project level moduel config (see Screenshot).

![image](https://user-images.githubusercontent.com/75415872/140335758-163eed78-c838-43be-a7cc-051c0864574d.png)

**Comment by jgardner-qha** [comment] 2021-11-04 16:55
I have confirmed that this is the problem by configuring a separate, identical REDCap instance. When using the local storage option, everything works as expected. When changing from local storage to any other option, the module stops working with the symptoms described at the top of this issue.
![image](https://user-images.githubusercontent.com/83370464/140383360-8856ae87-a728-4c5b-9404-3dac17023054.png)

Big thanks @tertek for your work on this module! It has very exciting possibilities and I would love to see some additional features. As I said before, I am not a programmer - however, I will gladly help in any way that I can with making any fixes or improvements. I'll toy with fixing this particular issue first, as I think it may be a relatively quick fix.

**Comment by jgardner-qha** [comment] 2021-11-04 19:04
@edbitao and @tertek, I found a fix for this. You can see from the pull request the code change - it is two very small changes in one file.

**Comment by tertek** [comment] 2021-11-05 07:16
@jgardner-qha I appreciate your investigation into this. Apologies for not seeing the problem, also @edbitao.

It was not clear to me that the hardcoded $EDOC_PATH was not generated dynamically taking different storage options into account. Also I did not realize that during Upload different storage options were taken into account.

Your fix is perfect and has been merged. Also a new module version has been submitted to the Repo.
I would appreciate more PR for other Features :)

**Closed by tertek** 2021-11-05 07:16 UTC
Labels: wontfix

**Comment by jgardner-qha** [comment] 2021-11-05 12:31
No apologies necessary! I'm happy that you concur and updated the repo, thank you very much, @tertek!
I am thinking of some other enhancements that would be nice - but I'll start another thread for them. I'll do what I can, but as I said I'm not a programmer - more of a sysadmin - so any new code I may contribute will have to be checked carefully. :)
